version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: always
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    #volumes:
    #  - ./frontend:/app
    restart: always
